# Common configuration.
AllCops:
  Excludes:
    - db/schema.rb
    - config/*

# Document classes and non-namespace modules.
Documentation:
  Exclude:
    - db/migrate
    - test

##################### Rails ##################################

# Use sexy validations.
Validation:
  Enabled: true
